version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
      - ./scripts/terraform-init-stage.sh
  build:
    commands:
      - ./scripts/terraform-destroy-stage.sh
      - ./scripts/additional-infrastructure-down-stage.sh
