version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
      - ./scripts/terraform-init-stage.sh
  build:
    commands:
      - ./scripts/terraform-plan-stage.sh
      - ./scripts/terraform-apply-stage.sh
