version: 0.2

phases:
  pre_build:
    commands:
      - ./scripts/echo-brand.sh
      - export PIPELINE_ID=$COYOTE_PIPELINE_ID
      - . ./scripts/assume-role.sh
      - . ./scripts/export-xilution-config.sh
      - . ./scripts/export-terraform-vars.sh stage
  build:
    commands:
      - ./scripts/terraform.sh stage up $TERRAFORM_PATH terraform.tfstate $TERRAFORM_PROVIDER
      - ./scripts/terraform.sh stage up $ADD_INFRA_TERRAFORM_PATH_STAGE additional-infrastructure.tfstate $TERRAFORM_PROVIDER
