version: 0.2

env:
  exported-variables:
    - SITE_BASE_URL

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
      - ./scripts/terraform-init-stage.sh
  build:
    commands:
      - ./scripts/deploy-up.sh
      - . ./scripts/export-site-base-url.sh
