version: 0.2

phases:
  pre_build:
    commands:
      - ./scripts/echo-brand.sh
      - export PIPELINE_ID=$COYOTE_PIPELINE_ID
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/deploy-up.sh
