version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - ./scripts/echo-brand.sh
      - export PIPELINE_ID=$COYOTE_PIPELINE_ID
      - . ./scripts/export-xilution-config.sh
  build:
    commands:
      - ./scripts/validate-config.sh xilution-content-delivery-coyote
      - ./scripts/verify.sh
